name: Diff summary

on:
  pull_request:
    branches:
      - master

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Run command before PR
        run: nix eval --raw '.#summary' > /tmp/before.txt

      - name: Pull Request Changes
        run: git pull --rebase origin pull/${{ github.event.pull_request.number }}/head

      - name: Run command after PR
        run: nix eval --raw '.#summary' > /tmp/after.txt

      - name: Generate diff
        run: diff -u0 -F':$' /tmp/before.txt /tmpafter.txt
