name: Update flake.lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 1 * *" # runs 1st of each month

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Generate summary before update
        run: nix eval --raw '.#summary' > /tmp/before.txt

      - name: Update flake.lock
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git branch -c update-flakelock
          nix flake update --commit-lock-file --commit-lock-file-summary "Update flake.lock"

      - name: Generate summary after update
        run: nix eval --raw '.#summary' > /tmp/after.txt

      - name: Generate diff
        run: diff -u0 -F':$' /tmp/before.txt /tmp/after.txt > /tmp/diff.txt || true

      - name: Save diff to env variable
        run: |
          EOF_TOKEN=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)
          echo "DIFF_OUTPUT<<$EOF_TOKEN" >> $GITHUB_ENV
          cat /tmp/diff.txt >> $GITHUB_ENV
          echo "$EOF_TOKEN" >> $GITHUB_ENV

      - name: Save commit message to env variable
        run: |
          EOF_TOKEN=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)
          echo "COMMIT_MSG<<$EOF_TOKEN" >> $GITHUB_ENV
          git log --format=%b -n1 >> $GITHUB_ENV
          echo "$EOF_TOKEN" >> $GITHUB_ENV

      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update flake.lock"
          body: |
            Update flake.lock

            ```
            ${{ env.COMMIT_MSG }}
            ```

            ```diff
            ${{ env.DIFF_OUTPUT }}
            ```
          head: update-flakelock
          base: master
