name: Update flake.lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 0" # runs weekly on Sunday at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Generate summary before update
        run: nix eval --raw '.#summary' > /tmp/before.txt

      - name: Update flake.lock
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git branch -c update-flakelock
          nix flake update --commit-lock-file --commit-lockfile-summary "Update flake.lock"

      - name: Generate summary after update
        run: nix eval --raw '.#summary' > /tmp/after.txt

      - name: Generate diff
        run: diff -u0 -F':$' /tmp/before.txt /tmp/after.txt > /tmp/diff.txt || true

      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update flake.lock"
          body: |
            Update flake.lock

            ```diff
            $(cat /tmp/diff.txt)
            ```
          head: update-flakelock
          base: master
